"use client";

/**
 * LEGAL overlay — DISCLAIMER / PRIVACY / TERMS (V1 single modal).
 * Same modal shell as WHAT CAN YOU DO? (8A.12); mobile overflow matches ENTER.
 */

import { useEffect, useId, useRef, type ReactNode } from "react";

type CanvasLegalNoteProps = {
  onClose: () => void;
};

export const LEGAL_CONTACT_EMAIL = "hi@4663.live" as const;
export const LEGAL_LAST_UPDATED = "Last updated: August 2026" as const;

const DISCLAIMER_PARAGRAPHS = [
  "4663 is an experimental shared canvas and information service.",
  "RADAR and other onchain features surface public Robinhood Chain data and analysis generated by 4663. Nothing on 4663 is financial, investment, trading, legal or tax advice.",
  "A token appearing on RADAR is not a recommendation, endorsement or signal to buy. It is something we think may be worth investigating further.",
  "Blockchain data, derived analysis and other information shown on 4663 may be delayed, incomplete or incorrect. Always verify information independently before acting on it.",
  "Interacting with tokens, smart contracts, wallets or third-party services involves risk. You are responsible for your own decisions and actions.",
  "Links to Blockscout, X or other third-party services are provided for convenience. Those services operate independently from 4663.",
] as const;

const PRIVACY_PARAGRAPHS = [
  "4663 does not require accounts, passwords or sign-ups.",
  "We use anonymous browser/session identifiers to support features such as presence, temporary participation and shared canvas activity. Some preferences are stored locally in your browser so they persist between visits.",
  "If you choose ENTER, your temporary display name may be visible to other people while you participate. Content you publish to the shared canvas or GLOBAL CHAT should be treated as public.",
  "4663 derives coarse location information from connection metadata supplied by our hosting infrastructure so we can show general presence information such as region or country. Application code does not store your IP address.",
  "GLOBAL CHAT messages are intended to remain visible for approximately 24 hours. Some expired or inactive records may remain in underlying systems for longer before they are physically removed.",
  "TEXT, DRAW and other shared canvas content may be temporary, may disappear when you leave or reset, and may be removed under the rules of the service.",
  "We use third-party infrastructure and service providers to host, operate and synchronise 4663. Normal technical information may be processed by those providers as part of delivering the service.",
  "RADAR displays public blockchain identifiers and transactions, including wallet addresses, token addresses and transaction hashes. These come from public blockchain data rather than private information submitted to 4663.",
  "For privacy questions or requests relating to information you believe is associated with you, contact:",
] as const;

const TERMS_PARAGRAPHS = [
  "By using 4663, you agree to use the service responsibly and lawfully.",
  "4663 is a shared public space. Do not publish unlawful, abusive, threatening, fraudulent, malicious or infringing content, spam, scams or content intended to harm other users or disrupt the service.",
  "Do not use 4663 to impersonate others, distribute malicious links or software, manipulate the service, or interfere with its infrastructure.",
  "You remain responsible for the content you publish. By placing content on the shared canvas or GLOBAL CHAT, you allow 4663 to display, transmit and process that content as needed to operate the service.",
  "Content may expire, be removed, become unavailable or be deleted as part of moderation, technical operation or changes to the service.",
  "4663 may restrict functionality, remove content or limit access where reasonably necessary to protect the service, users or infrastructure.",
  "Third-party websites, contracts, tokens and services linked or referenced through 4663 are outside our control. Your use of them is at your own risk.",
  "4663 is provided on an “as available” basis. Features, data and functionality may change, be interrupted or be discontinued.",
  "To the extent permitted by law, 4663 is not responsible for losses arising from reliance on information shown on the service, use of third-party services, blockchain activity or interruption of the service.",
  "These terms may be updated as 4663 evolves.",
] as const;

function Section({
  heading,
  paragraphs,
  after,
}: {
  heading: string;
  paragraphs: readonly string[];
  after?: ReactNode;
}) {
  return (
    <section data-4663-legal-section={heading.toLowerCase()}>
      <h3 className="font-semibold text-neutral-900">{heading}</h3>
      {paragraphs.map((paragraph) => (
        <p key={paragraph} className="mt-2">
          {paragraph}
        </p>
      ))}
      {after}
    </section>
  );
}

export function CanvasLegalNote({ onClose }: CanvasLegalNoteProps) {
  const titleId = useId();
  const closeRef = useRef<HTMLButtonElement>(null);
  const previouslyFocused = useRef<HTMLElement | null>(null);

  useEffect(() => {
    previouslyFocused.current =
      document.activeElement instanceof HTMLElement
        ? document.activeElement
        : null;
    closeRef.current?.focus();

    const onKeyDown = (event: KeyboardEvent) => {
      if (event.key === "Escape") {
        event.preventDefault();
        onClose();
      }
    };
    window.addEventListener("keydown", onKeyDown);

    const previousOverflow = document.body.style.overflow;
    document.body.style.overflow = "hidden";

    return () => {
      window.removeEventListener("keydown", onKeyDown);
      document.body.style.overflow = previousOverflow;
      previouslyFocused.current?.focus();
    };
  }, [onClose]);

  return (
    <div
      className="fixed inset-0 z-30 flex items-center justify-center overflow-y-auto overscroll-none bg-neutral-900/25 pt-[max(0.75rem,env(safe-area-inset-top,0px))] pr-[max(0.75rem,env(safe-area-inset-right,0px))] pb-[max(0.75rem,env(safe-area-inset-bottom,0px))] pl-[max(0.75rem,env(safe-area-inset-left,0px))] sm:p-6"
      data-4663-legal-backdrop
      data-4663-snapshot-exclude=""
      onMouseDown={(event) => {
        if (event.target === event.currentTarget) onClose();
      }}
      onPointerDown={(event) => {
        event.stopPropagation();
      }}
    >
      <div
        role="dialog"
        aria-modal="true"
        aria-labelledby={titleId}
        className="pointer-events-auto flex max-h-[calc(100dvh-1.5rem-env(safe-area-inset-top,0px)-env(safe-area-inset-bottom,0px))] w-full max-w-[min(24rem,calc(100vw-1.5rem))] flex-col overflow-y-auto overscroll-contain border border-neutral-300 bg-white px-4 py-4 text-neutral-900 shadow-sm sm:max-h-[min(40rem,calc(100dvh-3rem))] sm:max-w-md sm:px-6 sm:py-6"
        data-4663-legal-note
        onPointerDown={(event) => event.stopPropagation()}
      >
        <div className="mb-4 flex shrink-0 items-start justify-between gap-4">
          <div className="min-w-0">
            <h2
              id={titleId}
              className="font-mono text-sm font-semibold tracking-tight"
            >
              4663 // LEGAL
            </h2>
            <p className="mt-1 font-mono text-[10px] tracking-wide text-neutral-400 sm:text-[11px]">
              {LEGAL_LAST_UPDATED}
            </p>
          </div>
          <button
            ref={closeRef}
            type="button"
            onClick={onClose}
            className="inline-flex min-h-11 min-w-11 shrink-0 items-center justify-end font-mono text-[11px] tracking-wide text-neutral-400 transition-colors hover:text-neutral-700 focus-visible:outline focus-visible:outline-2 focus-visible:outline-offset-2 focus-visible:outline-neutral-400 sm:min-h-0 sm:min-w-0"
            aria-label="Close"
            data-4663-legal-close
          >
            [ CLOSE ]
          </button>
        </div>

        <div className="space-y-5 font-mono text-[12px] leading-relaxed tracking-wide text-neutral-600 sm:text-[13px]">
          <Section heading="DISCLAIMER" paragraphs={DISCLAIMER_PARAGRAPHS} />
          <Section
            heading="PRIVACY"
            paragraphs={PRIVACY_PARAGRAPHS}
            after={
              <p className="mt-2">
                <a
                  href={`mailto:${LEGAL_CONTACT_EMAIL}`}
                  className="break-all text-neutral-800 underline-offset-2 hover:underline focus-visible:outline focus-visible:outline-2 focus-visible:outline-offset-2 focus-visible:outline-neutral-400"
                  data-4663-legal-email
                >
                  {LEGAL_CONTACT_EMAIL}
                </a>
              </p>
            }
          />
          <Section heading="TERMS" paragraphs={TERMS_PARAGRAPHS} />

          <footer
            className="border-t border-neutral-200 pt-4"
            data-4663-legal-footer
          >
            <p>Questions about these terms or your privacy?</p>
            <p className="mt-1">
              <a
                href={`mailto:${LEGAL_CONTACT_EMAIL}`}
                className="break-all text-neutral-800 underline-offset-2 hover:underline focus-visible:outline focus-visible:outline-2 focus-visible:outline-offset-2 focus-visible:outline-neutral-400"
                data-4663-legal-email-footer
              >
                {LEGAL_CONTACT_EMAIL}
              </a>
            </p>
          </footer>
        </div>
      </div>
    </div>
  );
}
